# OpenAI AI服务配置模板
# 复制此文件为 openai_config.yaml 并填入真实的API密钥

# AI服务提供商
provider: openai

# OpenAI API配置
api_key: "your-openai-api-key-here"  # 必填: 从 https://platform.openai.com/api-keys 获取

# 模型配置
model: "gpt-4"                         # 可选: gpt-4, gpt-3.5-turbo 等
temperature: 0.1                      # 可选: 0.0-1.0, 控制创造性
max_tokens: 500                       # 可选: 最大响应长度

# 可选: 自定义API端点 (用于代理或其他兼容服务)
base_url: "https://api.openai.com/v1"

# 提示词配置
prompts:
  intent_recognition: |
    你是一个CRM系统的AI助手。请分析用户请求并识别操作意图。

    用户请求: "{user_input}"

    可能的操作类型:
    - create_customer: 创建客户
    - search_customers: 搜索客户
    - get_customer: 获取客户详情
    - update_customer: 更新客户信息
    - create_order: 创建订单
    - search_products: 搜索产品
    - create_lead: 创建销售线索

    请以JSON格式返回识别结果，包含intent、entities、confidence字段。

  entity_extraction: |
    从用户请求中提取实体信息:
    用户请求: "{user_input}"
    意图: {intent}

    请提取相关信息并以JSON格式返回。

# 高级配置
timeout: 30                           # 请求超时时间(秒)
retry_attempts: 3                      # 失败重试次数